
version: 2.0 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/repository # our name of the directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:12.13.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm run test-nowatch

  deploy: # deploy script
    working_directory: ~/repository
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # build react
          name: react-build
          command: npm run build
      - run: # make  copy of .firebaserc
          name: generate-firebaserc
          command: cp .firebaserc.example .firebaserc
      - run: # modify .firebaserc with env variable
          name: modify-firebaserc
          command: sed -i "s/\[YOUR\-PROJECT\-ID\]/$FIREBASE_PROJECT_ID/g" .firebaserc
      - run:
          name: Deploy Firebase
          # command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
          command: firebase deploy --project $FIREBASE_PROJECT_ID --only hosting

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build # perform this first
      - deploy: # perform second
          requires:
            - build
          filters: # only for the master branch
            branches:
              only: master